#ifndef CONFIG_H
#define CONFIG_H

// POST variables
#define WEATHER_KEY_LATITUDE 1
#define WEATHER_KEY_LONGITUDE 2
#define WEATHER_KEY_UNIT_SYSTEM 3

// Received variables
#define WEATHER_KEY_CURRENT 1
#define WEATHER_KEY_PRECIPITATION 3

//#define WEATHER_HTTP_COOKIE 1949999771
#define WEATHER_HTTP_COOKIE 1949327671

const char * const nameday_text[][31] = {
{
        "",
        "ALEXANDRA, KARINA",
        "DANIELA",
        "DRAHOSLAV",
        "ANDREA",
        "ANTÓNIA",
        "BOHUSLAVA",
        "SEVERÍN",
        "ALEXEJ",
        "DÁŠA",
        "MALVÍNA",
        "ERNEST",
        "RASTISLAV",
        "RADOVAN",
        "DOBROSLAV",
        "KRISTÍNA",
        "NATAŠA",
        "BOHDANA",
        "DRAHOMÍRA, MÁRIO",
        "DALIBOR",
        "VINCENT",
        "ZORA",
        "MILOŠ",
        "TIMOTEJ",
        "GEJZA",
        "TAMARA",
        "BOHUŠ",
        "ALFONZ",
        "GAŠPAR",
        "EMA",
        "EMIL"
},
{
        "TATIANA",
        "ERIKA, ERIK",
        "BLAŽEJ",
        "VERONIKA",
        "AGÁTA",
        "DOROTA",
        "VANDA",
        "ZOJA",
        "ZDENKO",
        "GABRIELA",
        "DEZIDER",
        "PERLA",
        "ARPÁD",
        "VALENTÍN",
        "PRAVOSLAV",
        "IDA, LIANA",
        "MILOSLAVA",
        "JAROMÍR",
        "VLASTA",
        "LÍVIA",
        "ELEONÓRA",
        "ETELA",
        "ROMAN, ROMANA",
        "MATEJ",
        "FREDERIK, FREDERIKA",
        "VIKTOR",
        "ALEXANDER",
        "ZLATICA",
        "RADOMÍR",
        "",
        ""
},
{
        "ALBÍN",
        "ANEŽKA",
        "BOHUMIL, BOHUMILA",
        "KAZIMÍR",
        "FRIDRICH",
        "RADOSLAV, RADOSLAVA",
        "TOMÁŠ",
        "ALAN, ALANA",
        "FRANTIŠKA",
        "BRUNO, BRANISLAV",
        "ANGELA, ANGELIKA",
        "GREGOR",
        "VLASTIMIL",
        "MATILDA",
        "SVETLANA",
        "BOLESLAV",
        "LUBICA",
        "EDUARD",
        "JOZEF",
        "VÍTAZOSLAV, KLAUDIUS",
        "BLAHOSLAV",
        "BENADIK",
        "ADRIÁN",
        "GABRIEL",
        "MARIÁN",
        "EMANUEL",
        "ALENA",
        "SONA",
        "MIROSLAV",
        "VIEROSLAVA",
        "BENJAMÍN"
},
{
        "HUGO",
        "ZITA",
        "RICHARD",
        "IZIDOR",
        "MIROSLAVA",
        "IRENA",
        "ZOLTÁN",
        "ALBERT",
        "MILENA",
        "IGOR",
        "JÚLIUS",
        "ESTERA",
        "ALEŠ",
        "JUSTINA",
        "FEDOR",
        "DANA, DANICA",
        "RUDOLF",
        "VALÉR",
        "JELA",
        "MARCEL",
        "ERVÍN",
        "SLAVOMÍR",
        "VOJTECH",
        "JURAJ",
        "MAREK",
        "JAROSLAVA",
        "JAROSLAV",
        "JARMILA",
        "LEA",
        "ANASTÁZIA",
        ""
},
{
        "",
        "ŽIGMUND",
        "GALINA",
        "FLORIÁN",
        "LESIA, LESANA",
        "HERMÍNA",
        "MONIKA",
        "INGRIDA",
        "ROLAND",
        "VIKTÓRIA",
        "BLAŽENA",
        "PANKRÁC",
        "SERVÁC",
        "BONIFÁC",
        "ŽOFIA, SOFIA",
        "SVETOZÁR",
        "GIZELA",
        "VIOLA",
        "GERTRÚDA",
        "BERNARD",
        "ZINA",
        "JÚLIA, JULIANA",
        "ŽELMÍRA",
        "ELA",
        "URBAN",
        "DUŠAN",
        "IVETA",
        "VILIAM",
        "VILMA",
        "FERDINAND",
        "PETRANA, PETRONELA"
},
{
        "ŽANETA",
        "XÉNIA, OXANA",
        "KAROLÍNA",
        "LENKA",
        "LAURA",
        "NORBERT",
        "RÓBERT",
        "MEDARD",
        "STANISLAVA",
        "MARGARÉTA",
        "DOBROSLAVA",
        "ZLATKO",
        "ANTON",
        "VASIL",
        "VÍT",
        "BLANKA, BIANKA",
        "ADOLF",
        "VRATISLAV",
        "ALFRÉD",
        "VALÉRIA",
        "ALOJZ",
        "PAULÍNA",
        "SIDÓNIA",
        "JÁN",
        "OLÍVIA, TADEÁŠ",
        "ADRIÁNA",
        "LADISLAV, LADISLAVA",
        "BEÁTA",
        "PETER, PAVOL, PETRA",
        "MELÁNIA",
        ""
},
{
        "DIANA",
        "BERTA",
        "MILOSLAV",
        "PROKOP",
        "CYRIL, METOD",
        "PATRIK, PATRÍCIA",
        "OLIVER",
        "IVAN",
        "LUJZA",
        "AMÁLIA",
        "MILOTA",
        "NINA",
        "MARGITA",
        "KAMIL",
        "HENRICH",
        "DRAHOMÍR",
        "BOHUSLAV",
        "KAMILA",
        "DUŠANA",
        "ILJA, ELIÁŠ",
        "DANIEL",
        "MAGDALÉNA",
        "OLGA",
        "VLADIMÍR",
        "JAKUB",
        "ANNA, HANA, ANITA",
        "BOŽENA",
        "KRIŠTOF",
        "MARTA",
        "LIBUŠA",
        "IGNÁC"
},
{
        "BOŽIDARA",
        "GUSTÁV",
        "JERGUŠ",
        "DOMINIKA, DOMINIK",
        "HORTENZIA",
        "JOZEFÍNA",
        "ŠTEFÁNIA",
        "OSKAR",
        "LUBOMÍRA",
        "VAVRINEC",
        "ZUZANA",
        "DARINA",
        "LUBOMÍR",
        "MOJMÍR",
        "MARCELA",
        "LEONARD",
        "MILICA",
        "ELENA, HELENA",
        "LÝDIA",
        "ANABELA, LILIANA",
        "JANA",
        "TICHOMÍR",
        "FILIP",
        "BARTOLOMEJ",
        "LUDOVÍT",
        "SAMUEL",
        "SILVIA",
        "AUGUSTÍN",
        "NIKOLA, NIKOLAJ",
        "RUŽENA",
        "NORA"
},
{
        "DRAHOSLAVA",
        "LINDA, REBEKA",
        "BELO",
        "ROZÁLIA",
        "REGINA",
        "ALICA",
        "MARIANNA",
        "MIRIAMA",
        "MARTINA",
        "OLEG",
        "BYSTRÍK",
        "MÁRIA, MARLENA",
        "CTIBOR",
        "LUDOMIL",
        "JOLANA",
        "LUDMILA",
        "OLYMPIA",
        "EUGÉNIA",
        "KONŠTANTÍN",
        "LUBOSLAV, LUBOSLAVA",
        "MATÚŠ",
        "MÓRIC",
        "ZDENKA",
        "LUBOŠ, LUBOR",
        "VLADISLAV, VLADISLAVA",
        "EDITA",
        "CYPRIÁN",
        "VÁCLAV",
        "MICHAL, MICHAELA",
        "JAROLÍM",
        ""
},
{
        "ARNOLD",
        "LEVOSLAV",
        "STELA",
        "FRANTIŠEK",
        "VIERA",
        "NATÁLIA",
        "ELIŠKA",
        "BRIGITA",
        "DIONÝZ",
        "SLAVOMÍRA",
        "VALENTÍNA",
        "MAXIMILIÁN",
        "KOLOMAN",
        "BORIS",
        "TERÉZIA",
        "VLADIMÍRA",
        "HEDVIGA",
        "LUKÁŠ",
        "KRISTIÁN",
        "VENDELÍN",
        "URŠULA",
        "SERGEJ",
        "ALOJZIA",
        "KVETOSLAVA",
        "AUREL",
        "DEMETER",
        "SABÍNA",
        "DOBROMILA",
        "KLÁRA",
        "ŠIMON, SIMONA",
        "AURÉLIA"
},
{
        "DENIS, DENISA",
        "",
        "HUBERT",
        "KAROL",
        "IMRICH",
        "RENÁTA",
        "RENÉ",
        "BOHUMÍR",
        "TEODOR",
        "TIBOR",
        "MARTIN, MAROŠ",
        "SVÄTOPLUK",
        "STANISLAV",
        "IRMA",
        "LEOPOLD",
        "AGNESA",
        "KLAUDIA",
        "EUGEN",
        "ALŽBETA",
        "FÉLIX",
        "ELVÍRA",
        "CECÍLIA",
        "KLEMENT",
        "EMÍLIA",
        "KATARÍNA",
        "KORNEL",
        "MILAN",
        "HENRIETA",
        "VRATKO",
        "ONDREJ, ANDREJ",
        ""
},
{
        "EDMUND",
        "BIBIÁNA",
        "OLDRICH",
        "BARBORA, BARBARA",
        "OTO",
        "MIKULÁŠ",
        "AMBRÓZ",
        "MARÍNA",
        "IZABELA",
        "RADÚZ",
        "HILDA",
        "OTÍLIA",
        "LUCIA",
        "BRANISLAVA, BRONISLAVA",
        "IVICA",
        "ALBÍNA",
        "KORNÉLIA",
        "SLÁVA",
        "JUDITA",
        "DAGMARA",
        "BOHDAN",
        "ADELA",
        "NADEŽDA",
        "ADAM, EVA",
        "",
        "ŠTEFAN",
        "FILOMÉNA",
        "IVANA, IVONA",
        "MILADA",
        "DÁVID",
        "SILVESTER"
}
};

const char * const moon_phase_text[] = {
        "NOV",
        "NOV+",
        "1. ŠT.",
        "SPL-",
        "SPLN",
        "SPL+",
        "3. ŠT.",
        "NOV-"
};

#endif
